---
title: "Check_Pop"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
<!-- # Pontos para checar: -->
<!-- #     - se GPS tem pontos além dos do dia -->
<!-- #     - se aba indivíduos entra para check -->
<!-- #   - evidências -->
<!-- #     - Se tem na pasta -->
<!-- #     - se as foos que estão na pasta tem a data correta -->
<!-- # ----  -->
<!-- # - Tempo decorrido desde o campo: -->
<!-- #   - 30 dias: -->
<!-- #     - se fotos foram triadas: -->
<!-- #       - se na pasta do campo - ver padrão a adotar -->
<!-- #   - 60 dias: -->
<!-- #     - se já rolaram as identificações -->

```{r setup, include=FALSE}
library(flexdashboard)
library(readxl)
library(dplyr)
library(lubridate)
library(stringr)

data_i = "01/04/2023"
data_f = "31/07/2023"

# Pastas/arquivos no servidor NAS
pasta_data <- "//nas_ipec/PBC-Pesquisa/PROJETOS/ANDAMENTO/01_FOTOID"
pasta_campo <- paste0(pasta_data, "/01_CAMPO")
pasta_scan <- paste0(pasta_campo, "/01_SCAN")
arquivo_excel <- paste0(pasta_campo, "/02_EXCEL/populacional_PBC.xlsx")
pasta_gps <- paste0(pasta_campo, "/03_GPS")
pasta_sonda <- paste0(pasta_campo, "/04_SONDA")
pasta_evidencias <- paste0(pasta_campo, "/05_EVIDENCIAS")
```

```{r dados-excel, include=FALSE}
# Pegar os dados de cada aba do excel filtrando entre as datas_i e data_f
datas_saidas <- 
  read_excel(arquivo_excel, sheet = "Saidas", col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "text")) %>%
  mutate(data = ymd(data)) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  select(data)

datas_amostragens <- 
  read_excel(arquivo_excel, sheet = "Amostragem", col_types = c("text", "date", "text", "text", "text", "text", "text")) %>%
  mutate(data = ymd(data)) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  group_by(data) %>%
  summarise(amostragens = n())

datas_clima <- 
  read_excel(arquivo_excel, sheet = "Clima", col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "text", "text")) %>%
  mutate(data = ymd(data)) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  group_by(data) %>%
  summarise(climas = n())

datas_avistagens <- 
  read_excel(arquivo_excel, sheet = "Avistagens", col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text")) %>%
  mutate(data = ymd(data)) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  group_by(data) %>%
  summarise(avistagens = n())

datas_pausa <- 
  read_excel(arquivo_excel, sheet = "Pausa", col_types = c("text", "date", "text", "text", "text")) %>%
  mutate(data = ymd(data)) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  group_by(data) %>%
  summarise(pausas = n())

datas_wpextra <- 
  read_excel(arquivo_excel, sheet = "WP_extra", col_types = c("text", "date", "text", "date", "text", "text", "text", "text")) %>%
  mutate(data = ymd(data)) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  group_by(data) %>%
  summarise(wps_extra = n())

datas_ids <- 
  read_excel(arquivo_excel, sheet = "Identificacoes", col_types = c("text", "date", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text", "text"), skip = 4) %>%
  mutate(data = ymd(data)) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  group_by(data) %>%
  summarise(ids = n())

```

```{r dados-pastas, include=FALSE}
info_scan <- 
  tibble(arquivo_scan = list.files(pasta_scan, pattern = "^.{14}.pdf")) %>%
  mutate(data = ymd(str_sub(arquivo_scan,5,14))) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  select(data, arquivo_scan)

info_gps <- 
  tibble(pasta = list.files(pasta_gps, pattern = ".{14}"),
         caminho = list.files(pasta_gps, pattern = ".{14}", full.names = TRUE)) %>%
  mutate(data = ymd(str_sub(pasta,5,14))) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  mutate(arquivo_trajecto = list.files(caminho, pattern = "Trajecto_\\d{4}-\\d{2}-\\d{2} \\d{6}.gpx"),
         arquivo_wp = list.files(caminho, pattern = "Pontos de passagem_\\d{2}-[A-Z]{3}-\\d{2}.gpx")) %>%
  select(data, arquivo_trajecto, arquivo_wp)

info_sonda <- 
  tibble(pasta = list.files(pasta_sonda, pattern = ".{14}"),
         caminho = list.files(pasta_sonda, pattern = ".{14}", full.names = TRUE)) %>%
  mutate(data = ymd(str_sub(pasta,5,14))) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  mutate(arquivo_sonda = list.files(caminho, pattern = ".xls")) %>%
  select(data, arquivo_sonda)

info_evidencias <- 
  tibble(pasta = list.files(pasta_evidencias, pattern = ".{14}"),
         caminho = list.files(pasta_evidencias, pattern = ".{14}", full.names = TRUE)) %>%
  mutate(data = ymd(str_sub(pasta,5,14))) %>%
  filter(data>dmy(data_i), data<dmy(data_f)) %>%
  rowwise() %>%
  mutate(n_evidencias = length(list.files(caminho, pattern = "JPG|jpg|JPEG|jpeg"))) %>%
  select(data, n_evidencias)
```

Básico
===================================== 

Column {data-width=500}
-----------------------------------------------------------------------

### MAPA

```{r}
paste("Preparar leaflet")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Resumo do excel

```{r}
datas_saidas %>%
  left_join(datas_amostragens, by = "data") %>%
  left_join(datas_clima, by = "data") %>%
  left_join(datas_avistagens, by = "data") %>%
  left_join(datas_pausa, by = "data") %>%
  left_join(datas_wpextra, by = "data") %>%
  left_join(datas_ids, by = "data") %>%
  replace(is.na(.), 0) %>%
  knitr::kable(align = "lcccccc")
```

### Resumo de arquivos

```{r}
datas_saidas %>%
  left_join(info_scan, by = "data") %>%
  left_join(info_sonda, by = "data") %>%
  left_join(info_gps, by = "data") %>%
  left_join(info_evidencias, by = "data") %>%
  knitr::kable(align = "lccccc")
```

Avançado
===================================== 
